<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\User;
use App\Models\Student;
use App\Models\ReportTemplate;
use Carbon\Carbon;

class ReportSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Clear existing reports to avoid duplicates
        DB::table('reports')->truncate();

        // 2. Fetch all students with relationships
        $students = Student::with(['daycare', 'parents'])->get();

        if ($students->isEmpty()) {
            $this->command->info('No students found. Run StudentSeeder first.');
            return;
        }

        // 3. Fetch teachers grouped by daycare for accurate "Generated By" attribution
        $teachersByDaycare = User::where('role', 'teacher')->get()->groupBy('daycare_id');
        $fallbackUser = User::first(); // Admin fallback if no teacher exists

        // 4. Fetch Templates ID Map
        $templates = ReportTemplate::all()->keyBy('name');

        $reports = [];
        $now = Carbon::now();

        $this->command->info("Generating reports for {$students->count()} students...");

        foreach ($students as $student) {
            // Find the correct teacher for this student's center
            $teacher = $teachersByDaycare->get($student->daycare_id)?->first() ?? $fallbackUser;

            // --- Common Variables ---
            $teacherName = "$teacher->first_name $teacher->last_name";
            $studentName = "$student->first_name $student->last_name";
            $daycareName = $student->daycare->name ?? "Main Center";

            // Format Parents: "Juan Cruz & Maria Cruz" or "Guardian..."
            $parentNames = $student->parents->isNotEmpty()
                ? $student->parents->map(fn($p) => "$p->first_name $p->last_name")->join(' & ')
                : "Guardian of $student->first_name";

            // Calculate precise age strings
            $dob = Carbon::parse($student->date_of_birth);
            $ageString = $dob->diff($now)->format('%y yrs, %m mos');
            $startAgeString = $dob->diff($now->copy()->subYear())->format('%y yrs');

            // ==========================================
            // REPORT 1: MONTHLY PROGRESS (Last Month)
            // ==========================================
            if (isset($templates['Monthly Progress Report'])) {
                $baseScore = rand(70, 95); // Random baseline for this student

                $chartData = [
                    ['name' => 'Week 1', 'score' => max(0, min(100, $baseScore - rand(0, 5)))],
                    ['name' => 'Week 2', 'score' => max(0, min(100, $baseScore - rand(0, 3)))],
                    ['name' => 'Week 3', 'score' => max(0, min(100, $baseScore + rand(0, 2)))],
                    ['name' => 'Week 4', 'score' => max(0, min(100, $baseScore + rand(1, 5)))],
                ];

                $content = [
                    'f1' => $studentName,
                    'f2' => $now->copy()->subDays(rand(2, 10))->format('Y-m-d'), // Random recent date
                    'f3' => $ageString,
                    'f4' => $daycareName,
                    'f5' => $teacherName,

                    'f6' => rand(80, 99), // Cognitive
                    'f7' => $this->getRandomObservation('cognitive'),
                    'f8' => rand(75, 98), // Physical
                    'f9' => $this->getRandomObservation('physical'),
                    'f10' => rand(85, 100), // Social
                    'f11' => $this->getRandomObservation('social'),
                    'f12' => $chartData,
                    'f13' => "• Vocabulary expansion\n• Fine motor skills\n• Peer interaction",
                    'f14' => "• Transition times\n• Focus during story time",
                    'f15' => 'Encourage more puzzle play at home to support cognitive growth.',
                ];

                $reports[] = [
                    'student_id' => $student->id,
                    'generated_by' => $teacher->id,
                    'report_type' => 'Monthly',
                    'report_date' => $content['f2'],
                    'content' => json_encode($content),
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }

            // ==========================================
            // REPORT 2: QUARTERLY ASSESSMENT
            // ==========================================
            if (isset($templates['Quarterly Developmental Assessment'])) {
                $motorChart = [
                    ['name' => 'Fine Motor', 'score' => rand(75, 95), 'fullMark' => 100],
                    ['name' => 'Gross Motor', 'score' => rand(80, 98), 'fullMark' => 100],
                    ['name' => 'Coordination', 'score' => rand(70, 90), 'fullMark' => 100],
                ];

                $content = [
                    'f1' => $studentName,
                    'f2' => $now->copy()->subWeeks(rand(2, 6))->format('Y-m-d'),
                    'f3' => $teacherName,
                    'f4' => '1st Quarter',
                    'f5' => $ageString,

                    'f6' => rand(82, 98),
                    'f7' => (bool)rand(0, 1), 'f8' => true, 'f9' => true,
                    'f10' => 'Shows great retention of daily routines and rules.',
                    'f11' => rand(80, 95), 'f12' => rand(85, 98),
                    'f13' => 'Balance is improving; loves outdoor play.',
                    'f14' => $motorChart,
                    'f15' => rand(85, 99), 'f16' => true, 'f17' => true,
                    'f18' => 'Verbal skills are developing rapidly; speaks in full sentences.',
                    'f19' => 'Identify complex shapes and patterns.',
                    'f20' => 'Pattern matching games and simple math.',
                    'f21' => $now->copy()->addMonths(3)->format('Y-m-d'),
                ];

                $reports[] = [
                    'student_id' => $student->id,
                    'generated_by' => $teacher->id,
                    'report_type' => 'Quarterly',
                    'report_date' => $content['f2'],
                    'content' => json_encode($content),
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }

            // ==========================================
            // REPORT 3: PARENT CONFERENCE
            // ==========================================
            if (isset($templates['Parent-Teacher Conference Form'])) {
                $content = [
                    'f1' => $studentName,
                    'f2' => $now->copy()->subDays(rand(10, 30))->format('Y-m-d'),
                    'f3' => $teacherName,
                    'f4' => $parentNames, // Uses Real Parent Names

                    'f5' => 'Meeting benchmarks well. Showing particular interest in arts and music.',
                    'f6' => 'Very social, natural leader among peers.',
                    'f7' => 'Responds well to positive reinforcement and helper roles.',
                    'f8' => 'Parents asked about nutritional options for lunch.',
                    'f9' => 'Child enjoys singing songs learned at school at home.',
                    'f10' => 'Improve focus during seated table activities.',
                    'f11' => 'Provide fidget toy during circle time if needed.',
                    'f12' => 'Ensure earlier bedtime to prevent morning fatigue.',
                    'f13' => $now->copy()->addMonths(3)->format('Y-m-d'),
                ];

                $reports[] = [
                    'student_id' => $student->id,
                    'generated_by' => $teacher->id,
                    'report_type' => 'Communication',
                    'report_date' => $content['f2'],
                    'content' => json_encode($content),
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }
        }

        // Insert in chunks to avoid memory issues if many students
        foreach (array_chunk($reports, 100) as $chunk) {
            DB::table('reports')->insert($chunk);
        }

        $this->command->info('Reports seeded successfully.');
    }

    /**
     * Helper to get random realistic observations
     */
    private function getRandomObservation($type)
    {
        $obs = [
            'cognitive' => [
                'Demonstrates strong problem-solving skills with puzzles.',
                'Can count to 20 and identify basic colors.',
                'Shows curiosity about how things work.',
                'Able to follow 2-step instructions clearly.'
            ],
            'physical' => [
                'Active participation in group physical activities.',
                'Fine motor skills improving; holding pencil correctly.',
                'Enjoys running and climbing during recess.',
                'Can stack 10 blocks without them falling.'
            ],
            'social' => [
                'Interacts positively with peers and staff.',
                'Shares toys willingly with classmates.',
                'Participates in group songs and dances.',
                'Show empathy when other children are upset.'
            ]
        ];

        return $obs[$type][array_rand($obs[$type])];
    }
}
